#!/bin/sh

METHOD_NAME=$1

if test -z "$METHOD_NAME"
then
    cat <<EOF
This program calls purple API functions using DBus.  As opposed to purple-send,
it does not print the return value.

Usage:

   $0 method-name type1:parameter1 type2:parameter2 ...

This shell script just invokes dbus-send, see man dbus-send for how
to specify the parameters.

Examples:

   $0 PurpleCoreQuit

Use dbus-viewer to get the list of supported functions and their parameters.
EOF
    exit 1
fi

shift
dbus-send --dest=im.pidgin.purple.PurpleService --type=method_call /im/pidgin/purple/PurpleObject im.pidgin.purple.PurpleInterface.$METHOD_NAME "$@"

